version: '3.8'

services:
  web:
    build: .
    container_name: django_faq
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: faq_db
      POSTGRES_USER: faq_user
      POSTGRES_PASSWORD: faq_password

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"  # Redis default port

volumes:
  postgres_data:  # Persistent data storage for PostgreSQL
